server:
  error:
    include-stacktrace: never
spring:
  data:
    mongodb:
      database: task-tracker-api
      auto-index-creation: true
  security:
    oauth2:
      resourceserver:
        jwt:
          audiences: https://task-tracker-api-594170868558.europe-west9.run.app
          issuer-uri: https://dajohnston.eu.auth0.com/
      client:
        registration:
          auth0:
            client-id: ${OAUTH_CLIENT_ID}
            client-secret: ${OAUTH_CLIENT_SECRET}
            authorization-grant-type: client_credentials
            provider: auth0
        provider:
          auth0:
            issuer-uri: https://dajohnston.eu.auth0.com/
management:
  endpoints:
    web:
      exposure:
        include: [ "health", "info", "metrics", "prometheus" ]
springdoc:
  group-configs:
    - group: Actuator
      paths-to-match: /actuator/**
    - group: Users
      paths-to-match: /users/**
    - group: User Info
      paths-to-match: /userinfo/**
  show-actuator: true
  swagger-ui:
    display-request-duration: true
    oauth:
      clientId: ${OAUTH_CLIENT_ID}
      clientSecret: ${OAUTH_CLIENT_SECRET}
