name: Java CI with Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    env:
      REPO: ${{ secrets.DOCKER_REPO }}
      DOCKER_BUILDKIT: 1
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Build
      run: docker build --target build .
    - name: Test
      run: docker build --progress=plain --build-arg 'MONGODB_USERNAME=${{ secrets.MONGODB_USERNAME }}' --build-arg 'MONGODB_PASSWORD=${{ secrets.MONGODB_PASSWORD }}' --build-arg 'MONGODB_HOST=${{ secrets.MONGODB_HOST }}' --build-arg 'SPRING_PROFILES_ACTIVE=${{ secrets.SPRING_PROFILES_ACTIVE }}' --build-arg 'MONGODB_DATABASE=housework_api_IT_${{ github.head_ref || github.ref_name }}' --target test .
    - name: Export Reports
      run: docker build --target results . --output out
    - name: Report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Gradle Tests
        path: out/test-results/**/*.xml
        reporter: java-junit
        fail-on-error: true
    - name: Sonar Main
      if: github.event.pull_request.base.ref == null
      run: docker build --build-arg SONAR_TOKEN=${{ secrets.SONAR_TOKEN }} --target sonar .
    - name: Sonar PR
      if: github.event.pull_request.base.ref != null
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: docker build --build-arg SONAR_TOKEN=${{ secrets.SONAR_TOKEN }} --build-arg sonar_pull_request_branch_name=${{ github.head_ref }} --build-arg sonar_pull_request_key=${{ github.event.number }} --build-arg sonar_pull_request_base=${{ github.event.pull_request.base.ref }} --target sonar-pr .
    - name: Log in to Docker Hub
      if: ${{ github.ref == 'refs/heads/main' }}
      run: docker login -u ${{ secrets.DOCKER_USER }}
        -p ${{ secrets.DOCKER_PASS }}
    - name: Build Docker image
      if: ${{ github.ref == 'refs/heads/main' }}
      run: docker build -t $REPO:latest -t $REPO:${GITHUB_SHA::8} .
    - name: Publish Docker image
      if: ${{ github.ref == 'refs/heads/main' }}
      run: docker push $REPO
    - name: Deploy
      if: ${{ github.ref == 'refs/heads/main' }}
      env:
        deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
      run: curl "$deploy_url"
