name: Java CI with Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build
      run: DOCKER_BUILDKIT=1 docker build --target build .
    - name: Test
      run: DOCKER_BUILDKIT=1 docker build --target test .
    - name: Export Reports
      run: DOCKER_BUILDKIT=1 docker build --target results . --output out
    - name: Report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Gradle Tests
        path: out/test-results/test/*.xml
        reporter: java-junit
        fail-on-error: true
    - name: Sonar
      run: DOCKER_BUILDKIT=1 docker build --build-arg SONAR_TOKEN=${{ secrets.SONAR_TOKEN }} --target sonar .
