name: Java CI with Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Build
      run: DOCKER_BUILDKIT=1 docker build --target build .
    - name: Test
      run: DOCKER_BUILDKIT=1 docker build --target test .
    - name: Export Reports
      run: DOCKER_BUILDKIT=1 docker build --target results . --output out
    - name: Report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Gradle Tests
        path: out/test-results/test/*.xml
        reporter: java-junit
        fail-on-error: true
    - name: Sonar Main
      if: github.event.pull_request.base.ref == null
      run: DOCKER_BUILDKIT=1 docker build --build-arg SONAR_TOKEN=${{ secrets.SONAR_TOKEN }} --target sonar .
    - name: Sonar PR
      if: github.event.pull_request.base.ref != null
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: DOCKER_BUILDKIT=1 docker build --build-arg SONAR_TOKEN=${{ secrets.SONAR_TOKEN }} --build-arg sonar_pull_request_branch_name=${{ github.head_ref }} --build-arg sonar_pull_request_key=${{ github.event.number }} --build-arg sonar_pull_request_base=${{ github.event.pull_request.base.ref }} --target sonar-pr .

